export const MINIMIZE_WINDOW = 'MINIMIZE_WINDOW';
export const CLOSE_WINDOW = 'CLOSE_WINDOW';
export const TRANSLATE = 'TRANSLATE';
export const WRITE_CLIPBOARD = {
  WRITE_CLIPBOARD_TEXT: 'WRITE_CLIPBOARD_TEXT',
};
